### ISSUE TITLE
CodeBuild SourceCredentials issue

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/coffee-store#1]
Got the following error when running deploy.sh
`Access token with server type GITHUB already exists. Delete its source credential and try again.`

I see that there is a cli command to delete the source credential. However, following questions come to mind:

- How can an AWS Account have multiple CodeBuild projects pointing to different repos?
- Deleted all existing CloudFormation stacks. No CodeBuild projects, still getting the same error.
Is there a recommended way to avoid error?

Thanks.

**Comment by asunar** [comment]
The SourceCredentials arn has a reference to the account id and the instructions explicitly say "account-wide". I assumed that my existing source credential was created by a CloudFormation stack and that deleting all the stacks would get rid of the existing source credential. It did not.

However, after manually deleting the existing SourceCredentialInfo via cli and running deploy.sh, SourceCredentialInfo is created successfully. I deleted the cloud formation stack created by deploy.sh and the SourceCredential was deleted as expected.

The script is working as expected. Looks like there was an existing SourceCredential in my account that was not associated with any of the existing Cloud Formation stacks.

Thanks for putting the series together.

**Comment by mikebroberts** [comment]
Glad you got it figured out. I don't particularly like how the CodeBuild team have built this "magic" credential location, for exactly the kind of problem you had here. I'd far rather be able to specify inline in the CodeBuild project resource (with a pointer to the Secrets Manager secret still).
