### ISSUE TITLE
Redundant Functional/End to end test examples

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/coffee-store#2]
Hello,

I was wondering if you could give a few examples of functional/end to end tests that you would NOT write as we go up the test pyramid. I've encountered this issue in several projects I worked on in the past. Legacy codebase, low test coverage so team agrees to write tests for new features. No one wants to be the person who says let's not write any more end to end tests :) 
Therefore, we sometimes end up with at least as many integration test/e2e tests as unit tests.

It would be great to learn about the principles to avoid the over-testing pitfalls. 

Thanks.

**Comment by mikebroberts** [comment]
To me the easier discussion to have is "what are we trying to test here?" . E.g. if what we are testing is something about how our code transforms data then that's a unit test. If on the other hand it's that we are assuming we get a certain structure of message in a Lambda event then that's an integration test. And if what you're testing has elements of both then that's probably a good opportunity to have two different tests. I do like a small number of "end-to-end" tests that make sure the whole system is properly connected together, but that's more of a sanity check than testing our code is correct.

**Comment by asunar** [comment]
That makes sense. Thanks.
