### ISSUE TITLE
deploy.sh command fails on CodeBuild

### ISSUE THREAD

**Issue by asunar** [symphoniacloud/coffee-store#4]
I was wondering if we need to explicitly grant execute permissions when running `./deploy.sh coffee-store-ci-test` in CodeBuild project.

Getting permission denied error in the build log.
![image](https://user-images.githubusercontent.com/204049/95607139-ee68aa00-0a20-11eb-894e-cf7e9cb03a85.png)

**Comment by mikebroberts** [comment]
You should make the file executable before committing to git. The deploy.sh in this repo is executable - if you look at it in Github you'll see this:
![image](https://user-images.githubusercontent.com/49635/95610933-18c16400-0a2f-11eb-8565-d9bdfefcc036.png)

**Comment by asunar** [comment]
That was it, thank you! I followed the instructions [here](https://stackoverflow.com/questions/21691202/how-to-create-file-execute-mode-permissions-in-git-on-windows) to make it executable.

**Comment by mikebroberts** [comment]
Great!
